### ISSUE TITLE
How to append a clickable href link?

### ISSUE THREAD

**Issue by dummerfranz** [ciar4n/Izmir#11]
Im having problems with appending a clickable href to a figure.
The width isnt expanding to 100%

`                    <a href="google.de">
                    <figure class="c4-izmir c4-border-top-left" style="width: 100%;height: 100%;">
                        <img src="https://source.unsplash.com/WLUHO9A_xik/400x300" alt="Sample Image">
                        <figcaption>
                            // Teamsport Bereich
                        </figcaption>
                    </figure>
                    </a>`

How to make an object clickable with a href?

**Comment by C-Lodder** [comment]
You're setting the `<figure>` to 100% width of the `<a>`.
Have you made sure the `<a>` has the correct width?

**Comment by dummerfranz** [comment]
yes works fine with any other element inside <a>
Except Izmir figures

height is working fine though

**Comment by dummerfranz** [comment]
solved the problem.
One must set padding: 0px;

Thanks for your help anyway
