### ISSUE TITLE
Microsoft Edge issue

### ISSUE THREAD

**Issue by vibranttheme** [ciar4n/Izmir#8]
HI,

Nice work done bro!! Can you please solve issue in case of Edge browser.

**Comment by C-Lodder** [comment]
@vibranttheme what issue are you having exactly? Which animation isn't working properly?

**Comment by vibranttheme** [comment]
Your demo https://ciar4n.com/izmir/ is not loaded in Microsoft Edge 40.15063.674.0

**Comment by ciar4n** [comment]
@vibranttheme I am unable to replicate any issues with MS Edge. Is the issue style-related? Could you paste a screenshot of your issue.

**Comment by C-Lodder** [comment]
Tested on Edge and Edge Chromium. Cannot replicate any issues
