### ISSUE TITLE
Not working on ios safari?

### ISSUE THREAD

**Issue by WhalenSITHS** [ciar4n/Izmir#9]
I have tried a few different permutations of this project but no matter what I do it remains broken on safari for me. I am using Nuxt in case that matters.

**Comment by C-Lodder** [comment]
Hi @WhalenSITHS, can you provide a screenshot from Safari?

**Comment by WhalenSITHS** [comment]
So once I added “onclick return true” to the whole component it began working. Several of the examples on the demo site don’t work on mobile.

**Comment by C-Lodder** [comment]
This library only contains CSS hover transitions and does NOT use any Javascript. If you're having to add `onclick="return true"` then I have to assume something is wrong on your end.

Are you sure you've posted this issue on the correct project repository?

**Comment by WhalenSITHS** [comment]
The hover effects on his own demo do not work on safari....only the top half do.  It’s pretty common technique to add onclick functions to elements to get them to hover correctly in Safari. Works fine on Firefox mobile.

**Comment by C-Lodder** [comment]
Oh you're talking about mobile. Well yes, touch devices do not have a "hover" event, so you're expected to tap on the element to initiate the transition.

**Comment by WhalenSITHS** [comment]
I understand how hover works on mobile. I’m telling you that it flat out does not work on safari. Even the examples on your site do not work. The bottom half of your examples do not work. The issue isn’t something I’m doing. I open the demo of the library and half the examples do not work on my iPhone X in Safari. The fix is adding the onclick function.

**Comment by C-Lodder** [comment]
I don't have Safari so could you do me a favour and copy the contents of this:

https://raw.githubusercontent.com/ciar4n/Izmir/master/izmir.css

and paste it in here:

https://autoprefixer.github.io

and then replace the contents of the CSS file you have with that of the generated content?

I could very well be down to the fact that certain properties don't contain the necessary prefixes.

**Comment by dgrammatiko** [comment]
Adding 
```css
pointer-events: all;
```
to the `c4-izmir` class resolves this. Demo: https://codepen.io/dgrammatiko/pen/eYJRBYj
